### PR TITLE
Bugfix/long strings

### PR DESCRIPTION
**Pull request by slabarque**
Hi

Nice work on the TcLog library! Great extendability!
I noticed that your TcLog only outputs 80 chars per line. This pull request introduces a (failing) test to demonstrate the issue.
- commit 95bf7fa "add unit test for long message strings"
  - I had to upgrade to a higher .net version, so I upgraded to NET 7.0
  - I created a unit test that logs a long message(255 chars), the message gets truncated.
  - I added extra content to the gitignore file in order to not check in *.dll, etc... into source control
- commit ac55947 "remove gitignored files"
  - this commit removes all the unnecessary files not need in source control
  - to git it looks like I've changed a lot of files, but I did not touch them, the only actual changes are in the previous commit

I've not yet looked into a fix for the issue of long strings, but wanted to launch this pull request anyway, maybe you have an easy way of fixing it. If I have time later I might look into a fix to make the unit test green...

### CODE REVIEW

**Comment by bengeisler** [comment]
Hi, thanks for reaching out and contributing! 👍 

The issue is fixed in 61e3f16. It turned out, the StringBuilder used `STRING` everywhere, which has a length of 80 by default. Using [T_MaxString](https://infosys.beckhoff.com/english.php?content=../content/1033/tcplclib_tc2_system/31062795.html&id=) instead solved it.  

I had to shorten the test string in the new unit test to account for the prefix in the log file which looks like this: `2023-03-24-01:18:43.702ErrorMAIN.testWrapper`. Prefix + new test string are of length 255 now and the test is passing.

**Comment by bengeisler** [comment]
Is this in a project where you are using the library or in the test project itself? It is working on my machine. 
You could check in `TcLogTest` -> `NET` -> `TestWrapper` -> Line 24: `fbTime(timeAsString => ActualTime);` if the time is correctly displayed when you're online on the (soft) plc and the program is running. If not, I'd dig into this `GenerateTimeData` function block and investigate further, until you reach the Beckhoff functions.

Also, the logger has to be called cyclically, like this, and has to finish with `RunLogger()`:
```
CoreLogger
	.IncludeInstancePath()
	.MinimumLevel(E_LogLevel.Warning)
	.SetDelimiter(delimiter)
	.SetRollingInterval(E_RollingInterval.Hourly)
	.DeleteLogFilesAfterDays(1)
	.TimestampFormat('_YYMMDD-hh-mm-ss_')
	.WriteToAds()
	.WriteToFile(filePath, fileName)
	.RunLogger();
```

**Comment by slabarque** [comment]
I'm using the library in a TcUnit test PRG. Here's what that looks like:
image
So I configure _logCore_ in the test PRG, on every cycle my test calls the _LogSut_ method which logs the _sut_ (Subject Under Test). I do realize that logging on every cycle might not be ideal and I would not do that in a production application, but this is for testing.

I already did some digging and looked into the code, when I call the _FB_LocalSystemTime_ myself like described in the [Beckhoff documentation](https://infosys.beckhoff.com/english.php?content=../content/1033/tcplclib_tc2_utilities/35008651.html&id=) I get a correct timestamp.

**Comment by slabarque** [comment]
I've investigated a bit and I'm getting the feeling that the code in `RunLogger` should wait for `TimeData.Done` before doing anything with files.
I also keeping getting the following error:
>Message		28/03/2023 13:37:53 958 ms | 'Tests_Task' (351): Closing file failed. Error thrown by FB_FileClose. Consult Beckhoff InfoSys. Internal Error: 1795				

Anyway I'm out of investigating time, a pity because I've not been able to get the logging to file to work properly...

**Pull request merged**
